name: CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - "**"
  schedule:
    # Friday 8am UTC (3am EST)
    - cron: "0 8 * * FRI"

jobs:
  build:
    # the OS must be GNU/Linux to be able to use the docker-coq-action
    runs-on: ubuntu-latest
    strategy:
      matrix:
        image:
          - "coqorg/coq:dev"
          - "coqorg/coq:8.13"
      fail-fast: false
    steps:
      - uses: actions/checkout@v2
      - uses: coq-community/docker-coq-action@v1
        with:
          opam_file: "coq-record-update-plugin.opam"
          custom_image: ${{ matrix.image }}
# See also:
# https://github.com/coq-community/docker-coq-action#readme
# https://github.com/erikmd/docker-coq-github-action-demo
